insert into public.jobs (
  slug,
  title,
  company,
  location,
  category,
  job_type,
  work_mode,
  experience,
  is_fresher,
  salary,
  apply_link,
  short_description,
  description,
  responsibilities,
  eligibility,
  warning,
  posted_at,
  source_name,
  source_url,
  skills,
  status,
  is_featured
)
values
  (
    'frontend-developer-vizag-studio',
    'Frontend Developer',
    'Vizag Studio',
    'Visakhapatnam',
    'IT',
    'Full-time',
    'Hybrid',
    '1-3 years',
    false,
    '4-6 LPA',
    'https://example.com/jobs/frontend-developer',
    'Build responsive React interfaces for a local product team.',
    'Join a product team building modern web experiences for companies in Vizag.',
    array['Build React UI components', 'Collaborate with designers', 'Improve frontend performance'],
    array['1+ years of React experience', 'Good CSS fundamentals', 'Strong communication skills'],
    'Never pay money to apply for a job.',
    timezone('utc', now()) - interval '1 day',
    'Company Careers',
    'https://example.com/careers',
    array['React', 'JavaScript', 'CSS'],
    'published',
    true
  ),
  (
    'customer-support-associate-fresher-vizag-connect',
    'Customer Support Associate',
    'Vizag Connect',
    'Visakhapatnam',
    'Support',
    'Full-time',
    'On-site',
    'Fresher',
    true,
    '2.4-3 LPA',
    'https://example.com/jobs/customer-support',
    'Entry-level support role for fresh graduates.',
    'Assist customers over phone and email while learning internal tools and workflows.',
    array['Answer customer queries', 'Document customer issues', 'Coordinate with internal teams'],
    array['Any degree', 'Basic English communication', 'Willingness to work in shifts'],
    'Verify job details before sharing personal documents.',
    timezone('utc', now()),
    'LinkedIn',
    'https://example.com/linkedin-job',
    array['Communication', 'Customer Support', 'CRM'],
    'published',
    false
  )
on conflict (slug) do nothing;
